---
name: "Main Workflow"
on: push
jobs:
  main:
    name: "Main"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Lint"
        run: npx ng lint

      - name: "Build"
        run: npx ng build

      - name: "Test"
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: "E2E Test"
        uses: cypress-io/github-action@v6
        with:
          start: npx ng serve

      - name: "Build Docker Image"
        run: docker build -t actio -f docker/Dockerfile .

      - name: "Release"
        run: npx semantic-release
        env:
          DOCKER_USERNAME: "CI"
