---
name: "Main Workflow"
on: push
jobs:
  main:
    name: "Main"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Lint"
        run: npx ng lint

      - name: "Test"
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: "Build"
        run: npx ng build

      - name: "Build Docker Image"
        run: docker build -t actio -f docker/Dockerfile .
